title: Race Taxi
email: ivoivicha@gmail.com
description: A place to join our Race Taxi and make your dreams come true!
destination: docs 
baseurl: "/race-taxi" 
url: "" 
twitter_username: jekyllrb
github_username:  jekyll

exclude: [_assets, node_modules, Gemfile, Gemfile.lock, gulpfile.js, package.json, package-lock.json, README.md]

markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
